version: 2
# doc and options for this file :
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

updates:
  # keep automatic actions up-to-date with the last version
  # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week on Saturday
      interval: "weekly"
      day: "saturday"
    reviewers:
      - pifou25
    # Branch to create pull requests against
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/build/"
    schedule:
      interval: "weekly"
      day: "saturday"
    reviewers:
      - pifou25
    target-branch: "develop"