# version: '2.3'

services:

  nginx:
    image: jc21/nginx-proxy-manager:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' # admin access
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${MYSQL_NPM_USER}"
      DB_MYSQL_PASSWORD: "${MYSQL_NPM_PASSWORD}"
      DB_MYSQL_NAME: "${MYSQL_NPM_USER}"
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 1m
      timeout: 3s


  db:
    image: yobasystems/alpine-mariadb:10
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 1m30s
      retries: 3
      start_period: 40s
      timeout: 20s
    volumes:
      - ./data/mysql:/var/lib/mysql
      # sh scripts for db initialization
      - ./init.db/script:/scripts/pre-init.d
      # sql or sql.tar.gz init data
      - ./init.db/sql:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "10m"
        max-file: "1"



  jeedom:
    # build: ./php
    image: pifou25/jeedom:light
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?required value}
      - MYSQL_JEEDOM_DATABASE=${MYSQL_DATABASE:-jeedom}
      - MYSQL_JEEDOM_USER=${MYSQL_USER:-jeedom}
      - MYSQL_JEEDOM_PASSWD=${MYSQL_PASSWORD:?required value}
      - JEEDOM_BRANCH=beta
      - MYSQL_HOST=db
      - TZ=${TIME_ZONE}
    hostname: jeedom
    restart: unless-stopped
    volumes:
      - ./jeedom:/var/www/html
      - ./backup:/tmp/backup
    healthcheck:
      test: ["CMD-SHELL", "curl -so /tmp/status http://localhost/here.html || exit 1"]
      interval: 1m30s
      retries: 3
      start_period: 40s
      timeout: 20s
    labels:
      # label chadburn for the "cron" container
      chadburn.enabled: "true"
      chadburn.job-exec.jeedom-cron.schedule: "@every 1m"
      chadburn.job-exec.jeedom-cron.command: "/usr/local/bin/php /var/www/html/core/php/jeeCron.php >> /var/www/html/log/cron.log 2>&1"
      # label for watchtower: don't check
      com.centurylinklabs.watchtower.enable: false
    depends_on:
      - db
      - scheduler
    logging:
      options:
        max-size: "10m"
        max-file: "1"


  # Scheduler Service: mcuadros/ofelia or premoweb/chadburn
  scheduler:
    image: premoweb/chadburn
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # command: --config=/config/config.ini
    logging:
      options:
        max-size: "10m"
        max-file: "1"


  phpmyadmin:
    image: phpmyadmin:5.0
    depends_on:
      - db
    logging:
      options:
        max-size: "10m"
        max-file: "1"


  portainer:
    image: portainer/portainer-ce
    privileged: true
    environment:
      - TZ=${TIME_ZONE}
    ports:
        - 8000:8000
        - 9000:9000
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/portainer:/data
    logging:
      options:
        max-size: "10m"
        max-file: "1"


  zwave:
    image: zwavejs/zwave-js-ui:8
    ports:
      - 3000:3000 # Z-Wave JS websocket server
      - 8091:8091 # Web Interface
    environment:
      - TZ=${TIME_ZONE}
    devices:
    #  - "/dev/ttyUSB0"
    #  - "/dev/ttyUSB1"
      - "/dev/ttyACM0"
    volumes:
      - ./data/zwave:/usr/src/app/store
    restart: unless-stopped
    depends_on:
      - mqtt
    healthcheck: # check if both mqtt and zwave client are connected
      test: ["CMD-SHELL", "curl localhost:8091/health/zwave -H \"Accept: text/plain\""]
      interval: 2m30s
      retries: 3
      start_period: 40s
      timeout: 20s
    logging:
      options:
        max-size: "10m"
        max-file: "1"


  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883 # only required to expose service on host
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./data/mosquitto/log:/mosquitto/log
      - ./data/mosquitto/data:/mosquitto/data
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "1"


  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      # - /root/.docker/config.json:/config.json
    command: --schedule "0 55 3 * * *"


  bitwarden:
    image: vaultwarden/server
    volumes:
      - ./data/vaultwarden:/data
    environment:
      - DATABASE_URL=mysql://${MYSQL_VAULT_USER}:${MYSQL_VAULT_PASSWORD}@db/${MYSQL_VAULT_USER}
    depends_on:
      - db
