name: Docker Multiplatform Build ci

on:
  push:
    branches:
      - 'workflow'

# no workflow concurrency, cancel previous running workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
      
jobs:
  jeedomSource:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Composer install Jeedom source
        # https://github.com/marketplace/actions/build-and-push-docker-images
        uses: docker/build-push-action@v5
        with:
          context: build/Dockerfile.source
          push: true
          tags: | 
            ghcr.io/${{ secrets.DOCKER_USER }}/jeedom:source


  matrix_jobs:
    runs-on: ubuntu-latest
    needs: jeedomSource
    strategy:
      matrix:
        debian: ["buster", "bullseye", "bookworm"]
        php: [7.3, 8.1]
        jeedom: ["V4-stable", "beta"]
        target: ["light", "full"]
        xdebug: [true, false]
        exclude:
          - debian: "bookworm"
            php: 7.3
          - debian: "buster"
            jeedom: "beta"
          - debian: "buster"
    steps:
      - name: "${{ matrix.debian }} PHP${{ matrix.php }} target ${{ matrix.target }} branch ${{ matrix.jeedom }} debug ${{ matrix.xdebug }}"
        id: buildJeedom
        continue-on-error: true
        run: |
          echo "${{ matrix.debian }} PHP${{ matrix.php }} target ${{ matrix.target }} branch ${{ matrix.jeedom }} debug ${{ matrix.xdebug }} 🚀" >> $GITHUB_STEP_SUMMARY
          echo docker ps
      - name: Check on failures
        if: steps.buildJeedom.outcome != 'success'
        run: echo "${{ matrix.debian }} PHP${{ matrix.php }} target ${{ matrix.target }} branch ${{ matrix.jeedom }} debug ${{ matrix.xdebug }} has ERRORS!"
        