name: Docker Multiplatform Build ci

on:
  push:
    branches:
      - 'matrix'

 
jobs:

  jbuild:
    # https://docs.docker.com/build/ci/github-actions/multi-platform/
    # distributebuild across multiple runners
    # This step  build the same image on different runners / platforms
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian: "buster"
            php: 7.3
          - debian: "bullseye"
            php: 7.4
          - debian: "bullseye"
            php: 8.1
          - debian: "bookworm"
            php: 8.2
        # linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
        platform:
          - name: "amd64"
            runson: "ubuntu-latest"
          - name: "arm64"
            runson: "self-hosted"
          - name: "arm/v6"
            runson: "self-hosted"
          - name: "arm/v7"
            runson: "self-hosted"
        jeedom: ["V4-stable", "beta"]
        target: ["light", "full"]
        xdebug: [true, false]
        exclude:
          # exclude Jeedom beta on every buster, not supported
          - os:
              debian: "buster"
            jeedom: "beta"
          # exclude Jeedom debug on every buster, useless
          - os:
              debian: "buster"
            xdebug: false

    env:
      REGISTRY_IMAGE: pifou25/jeedom
      TAG_NAME: ${{ matrix.os.debian }}-${{ matrix.os.php }}${{ matrix.target == 'light' && '-light' || '' }}${{ matrix.jeedom == 'beta' && '-beta' || '' }}${{ matrix.xdebug && '-debug' || '' }}${{ github.ref_name != 'master' && '-dev' || '' }}
      TAG_LATEST_ENABLED: ${{ (matrix.os.debian == 'bullseye' && matrix.os.php == 7.3 && matrix.target == 'full' && matrix.jeedom == 'V4-stable' && matrix.target == 'full' && matrix.xdebug == 'false' && github.ref_name == 'master') }}

    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Prepare ${{ env.TAG_LATEST_ENABLED && 'LATEST' ||'' }} ${{ env.TAG_NAME }}:${{ matrix.platform.name }}:${{ matrix.os }}
        # replace /  by - in platform value
        run: |
          platform=linux/${{ matrix.platform.name }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          echo "${TAG_NAME}:${PLATFORM_PAIR}:${{ matrix.os }}" >> $GITHUB_STEP_SUMMARY
